### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by GuilhermeQuirinoS** [ndhao164/Rise-of-Kingdoms-Bot#2]
Hey men,

I saw that you created the last version of Rise Of kindoms bot from yuceltoluyag for LDP Player. I want to put me as colaborator for the project if u need assitance to create or improve features

**Comment by GuilhermeQuirinoS** [comment]
Also, I'm trying to use the LDPlayer version, but it seems that it doesn't have the gems collect feature. Is that right?

**Comment by ndhao164** [comment]
Right, i developing feature collect gem

**Comment by GuilhermeQuirinoS** [comment]
for Bluestack version is it working?

**Comment by ndhao164** [comment]
Maybe no. I just use ldplayer so i edited code from bluestack to ldplayer
