### ISSUE TITLE
City Image

### ISSUE THREAD

**Issue by jooooooooo2** [ndhao164/Rise-of-Kingdoms-Bot#3]
Hey Mate, 

first of all, thanks for your work!

i have some questions.

1. Loading City Image, doesnt work for me. (adb enabled, reso 1280x780 240dpi)
2. can you show me your LDP settings ?
3. 
![{F36E9997-3FBE-48A0-A35F-F5B53D766F8F}](https://github.com/user-attachments/assets/33faf6c7-9f3b-46e2-85ce-4d888526cb67)
what do i chose here ?

much love and thanks!

**Comment by jooooooooo2** [comment]
![{F36E9997-3FBE-48A0-A35F-F5B53D766F8F}](https://github.com/user-attachments/assets/5bca47ad-6565-401d-b100-dfb10df9c152)

**Comment by ndhao164** [comment]
Choose Open local connection

**Comment by jooooooooo2** [comment]
any tips for the city imgage problem ?

**Comment by ndhao164** [comment]
can you share me log on terminal when taking error ? or contact with me via discord #hdz8140
